{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chaosplane.fullname" . }}-daemon
  labels:
    {{- include "chaosplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemon
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
{{- end }}
