apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaosplane-operator
  namespace: chaosplane-system
  labels:
    app.kubernetes.io/name: chaosplane
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosplane-operator
  labels:
    app.kubernetes.io/name: chaosplane
    app.kubernetes.io/component: operator
rules:
  - apiGroups: ["chaos.chaosplane.dev"]
    resources:
      - chaosexperiments
      - chaosexperiments/status
      - chaosworkflows
      - chaosworkflows/status
      - chaosschedules
      - chaosschedules/status
      - chaosagents
      - chaosagents/status
      - blastradiuspolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/eviction
      - nodes
      - services
      - configmaps
      - persistentvolumeclaims
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaosplane-operator
  labels:
    app.kubernetes.io/name: chaosplane
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaosplane-operator
subjects:
  - kind: ServiceAccount
    name: chaosplane-operator
    namespace: chaosplane-system
