//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ChaosExperiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosExperiment) DeepCopy() *ChaosExperiment {
	if in == nil {
		return nil
	}
	out := new(ChaosExperiment)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosExperiment) DeepCopyInto(out *ChaosExperiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ChaosExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosExperimentList) DeepCopy() *ChaosExperimentList {
	if in == nil {
		return nil
	}
	out := new(ChaosExperimentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosExperimentList) DeepCopyInto(out *ChaosExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosExperiment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosExperimentSpec) DeepCopyInto(out *ChaosExperimentSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Action.DeepCopyInto(&out.Action)
	out.Duration = in.Duration
	if in.Rollback != nil {
		in, out := &in.Rollback, &out.Rollback
		*out = new(RollbackSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Execution.DeepCopyInto(&out.Execution)
	if in.SteadyState != nil {
		in, out := &in.SteadyState, &out.SteadyState
		*out = new(SteadyStateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AbortConditions != nil {
		in, out := &in.AbortConditions, &out.AbortConditions
		*out = make([]AbortConditionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AbortConditionSpec) DeepCopyInto(out *AbortConditionSpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusProbe)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPProbe)
		**out = **in
	}
	if in.K8s != nil {
		in, out := &in.K8s, &out.K8s
		*out = new(K8sProbe)
		**out = **in
	}
}

func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *RollbackSpec) DeepCopyInto(out *RollbackSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(int32)
		**out = **in
	}
}

func (in *ChaosExperimentStatus) DeepCopyInto(out *ChaosExperimentStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.RecoveryStartTime != nil {
		in, out := &in.RecoveryStartTime, &out.RecoveryStartTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AffectedResources != nil {
		in, out := &in.AffectedResources, &out.AffectedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *BlastRadiusPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BlastRadiusPolicy) DeepCopy() *BlastRadiusPolicy {
	if in == nil {
		return nil
	}
	out := new(BlastRadiusPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *BlastRadiusPolicy) DeepCopyInto(out *BlastRadiusPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *BlastRadiusPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BlastRadiusPolicyList) DeepCopy() *BlastRadiusPolicyList {
	if in == nil {
		return nil
	}
	out := new(BlastRadiusPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *BlastRadiusPolicyList) DeepCopyInto(out *BlastRadiusPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlastRadiusPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BlastRadiusPolicySpec) DeepCopyInto(out *BlastRadiusPolicySpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	in.TargetLimits.DeepCopyInto(&out.TargetLimits)
	in.ProtectedResources.DeepCopyInto(&out.ProtectedResources)
	if in.ActionLimits != nil {
		in, out := &in.ActionLimits, &out.ActionLimits
		*out = new(ActionLimitsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeWindows != nil {
		in, out := &in.TimeWindows, &out.TimeWindows
		*out = new(TimeWindowsSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TimeWindowsSpec) DeepCopyInto(out *TimeWindowsSpec) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]TimeWindow, len(*in))
		copy(*out, *in)
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = make([]TimeWindow, len(*in))
		copy(*out, *in)
	}
}

func (in *ScopeSpec) DeepCopyInto(out *ScopeSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TargetLimitsSpec) DeepCopyInto(out *TargetLimitsSpec) {
	*out = *in
	if in.MaxTargets != nil {
		in, out := &in.MaxTargets, &out.MaxTargets
		*out = new(int32)
		**out = **in
	}
	if in.MaxPercentage != nil {
		in, out := &in.MaxPercentage, &out.MaxPercentage
		*out = new(int32)
		**out = **in
	}
}

func (in *ProtectedResourcesSpec) DeepCopyInto(out *ProtectedResourcesSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]ProtectedResource, len(*in))
		copy(*out, *in)
	}
}

func (in *ActionLimitsSpec) DeepCopyInto(out *ActionLimitsSpec) {
	*out = *in
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *SteadyStateSpec) DeepCopyInto(out *SteadyStateSpec) {
	*out = *in
	if in.Before != nil {
		in, out := &in.Before, &out.Before
		*out = make([]ProbeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = make([]ProbeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RecoveryTimeout = in.RecoveryTimeout
}

func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusProbe)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPProbe)
		**out = **in
	}
	if in.K8s != nil {
		in, out := &in.K8s, &out.K8s
		*out = new(K8sProbe)
		**out = **in
	}
}

func (in *PrometheusProbe) DeepCopyInto(out *PrometheusProbe) {
	*out = *in
}

func (in *ProbeCondition) DeepCopyInto(out *ProbeCondition) {
	*out = *in
}

func (in *HTTPProbe) DeepCopyInto(out *HTTPProbe) {
	*out = *in
}

func (in *K8sProbe) DeepCopyInto(out *K8sProbe) {
	*out = *in
}

func (in *K8sProbeCondition) DeepCopyInto(out *K8sProbeCondition) {
	*out = *in
}

func (in *ChaosWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosWorkflow) DeepCopy() *ChaosWorkflow {
	if in == nil {
		return nil
	}
	out := new(ChaosWorkflow)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosWorkflow) DeepCopyInto(out *ChaosWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ChaosWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosWorkflowList) DeepCopy() *ChaosWorkflowList {
	if in == nil {
		return nil
	}
	out := new(ChaosWorkflowList)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosWorkflowList) DeepCopyInto(out *ChaosWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosWorkflowSpec) DeepCopyInto(out *ChaosWorkflowSpec) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]WorkflowTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]WorkflowParameter, len(*in))
		copy(*out, *in)
	}
	out.ErrorHandling = in.ErrorHandling
	in.Execution.DeepCopyInto(&out.Execution)
}

func (in *ChaosWorkflowStatus) DeepCopyInto(out *ChaosWorkflowStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.TemplateStatuses != nil {
		in, out := &in.TemplateStatuses, &out.TemplateStatuses
		*out = make([]TemplateStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *WorkflowTemplate) DeepCopyInto(out *WorkflowTemplate) {
	*out = *in
	if in.ExperimentRef != nil {
		in, out := &in.ExperimentRef, &out.ExperimentRef
		*out = new(ExperimentRef)
		**out = **in
	}
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(DelaySpec)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionSpec)
		**out = **in
	}
	if in.Parallel != nil {
		in, out := &in.Parallel, &out.Parallel
		*out = new(ParallelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(SuspendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ParallelSpec) DeepCopyInto(out *ParallelSpec) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SuspendSpec) DeepCopyInto(out *SuspendSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *WorkflowExecutionSpec) DeepCopyInto(out *WorkflowExecutionSpec) {
	*out = *in
	if in.MaxParallelism != nil {
		in, out := &in.MaxParallelism, &out.MaxParallelism
		*out = new(int32)
		**out = **in
	}
}

func (in *TemplateStatus) DeepCopyInto(out *TemplateStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}
