//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ChaosExperiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosExperiment) DeepCopy() *ChaosExperiment {
	if in == nil {
		return nil
	}
	out := new(ChaosExperiment)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosExperiment) DeepCopyInto(out *ChaosExperiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ChaosExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChaosExperimentList) DeepCopy() *ChaosExperimentList {
	if in == nil {
		return nil
	}
	out := new(ChaosExperimentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ChaosExperimentList) DeepCopyInto(out *ChaosExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosExperiment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChaosExperimentSpec) DeepCopyInto(out *ChaosExperimentSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Action.DeepCopyInto(&out.Action)
	out.Duration = in.Duration
	if in.Rollback != nil {
		in, out := &in.Rollback, &out.Rollback
		*out = new(RollbackSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Execution.DeepCopyInto(&out.Execution)
}

func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *RollbackSpec) DeepCopyInto(out *RollbackSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(int32)
		**out = **in
	}
}

func (in *ChaosExperimentStatus) DeepCopyInto(out *ChaosExperimentStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BlastRadiusPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BlastRadiusPolicy) DeepCopy() *BlastRadiusPolicy {
	if in == nil {
		return nil
	}
	out := new(BlastRadiusPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *BlastRadiusPolicy) DeepCopyInto(out *BlastRadiusPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *BlastRadiusPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BlastRadiusPolicyList) DeepCopy() *BlastRadiusPolicyList {
	if in == nil {
		return nil
	}
	out := new(BlastRadiusPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *BlastRadiusPolicyList) DeepCopyInto(out *BlastRadiusPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlastRadiusPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BlastRadiusPolicySpec) DeepCopyInto(out *BlastRadiusPolicySpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	in.TargetLimits.DeepCopyInto(&out.TargetLimits)
	in.ProtectedResources.DeepCopyInto(&out.ProtectedResources)
	if in.ActionLimits != nil {
		in, out := &in.ActionLimits, &out.ActionLimits
		*out = new(ActionLimitsSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ScopeSpec) DeepCopyInto(out *ScopeSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TargetLimitsSpec) DeepCopyInto(out *TargetLimitsSpec) {
	*out = *in
	if in.MaxTargets != nil {
		in, out := &in.MaxTargets, &out.MaxTargets
		*out = new(int32)
		**out = **in
	}
	if in.MaxPercentage != nil {
		in, out := &in.MaxPercentage, &out.MaxPercentage
		*out = new(int32)
		**out = **in
	}
}

func (in *ProtectedResourcesSpec) DeepCopyInto(out *ProtectedResourcesSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]ProtectedResource, len(*in))
		copy(*out, *in)
	}
}

func (in *ActionLimitsSpec) DeepCopyInto(out *ActionLimitsSpec) {
	*out = *in
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}
